---
- hosts: Direct


  tasks:
        - name: List Home Directory Content
          shell:  "ls /home | awk '!/clientadmin|ht400|htadmin|lost+found|nagios|hmsadmin|root/' | sort" 
          register: directories
       
        - name: Get Hostname
          shell: hostname
          register: hostname


          #        - name: Write Directories
          #copy:
          #       content: "{{ directories.stdout }}"
          #       dest: "/home/htadmin/directories.txt"

        - name: Use extracted info
          with_items: "{{hostname.stdout_lines}} {{directories.stdout_lines | sort}}"
          debug: msg="these are the Directories Found" 
          
                  
         


...
