---
- hosts: provision


  tasks:
        - name: Get NTP Statistics
          shell:  "ntpstat" 
          register: ntpstat
       
        - name: Get Hostname
          shell: hostname
          register: hostname


          #        - name: Write Directories
          #copy:
          #       content: "{{ directories.stdout }}"
          #       dest: "/home/htadmin/directories.txt"

        - name: Use extracted info
          with_items: "{{hostname.stdout_lines}} {{ntpstat.stdout_lines | sort}}"
          debug: msg="these are the NTP Statistics Results" 
          
                  
         


...
